# Generated by Django 3.2 on 2021-04-24 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
