# Generated by Django 3.2 on 2021-04-24 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import roadmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_goal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[roadmap.models.validate_deadline_is_not_past]),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, validators=[roadmap.models.validate_deadline_is_not_past])),
                ('parent_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap.goal')),
            ],
        ),
    ]
