# Generated by Django 3.2 on 2021-04-25 02:35

from django.db import migrations, models
import django.utils.timezone
import roadmap.models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_auto_20210424_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, validators=[roadmap.models.validate_deadline_is_not_past]),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, validators=[roadmap.models.validate_deadline_is_not_past]),
        ),
    ]
